/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javadoggroomingapp.ui;

/**
 *
 * @author Lenovo
 */
public class AddForm extends javax.swing.JFrame {

    /**
     * Creates new form AddForm
     */
    public AddForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Appointment");
        setMaximumSize(new java.awt.Dimension(350, 2147483647));
        setMinimumSize(new java.awt.Dimension(350, 82));
        setPreferredSize(new java.awt.Dimension(350, 400));
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 10));

        jPanel31.setBackground(new java.awt.Color(204, 204, 204));
        jPanel31.setLayout(new java.awt.GridLayout(1, 2));

        jPanel32.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("Date");
        jPanel32.add(jLabel10);

        jPanel31.add(jPanel32);

        jPanel33.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jTextField9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField9.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel33.add(jTextField9);

        jPanel31.add(jPanel33);

        jPanel30.add(jPanel31);

        getContentPane().add(jPanel30);

        jPanel27.setBackground(new java.awt.Color(204, 204, 204));
        jPanel27.setLayout(new java.awt.GridLayout(1, 2));

        jPanel28.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Time");
        jPanel28.add(jLabel9);

        jPanel27.add(jPanel28);

        jPanel29.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jTextField8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField8.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel29.add(jTextField8);

        jPanel27.add(jPanel29);

        jPanel26.add(jPanel27);

        getContentPane().add(jPanel26);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jPanel8.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Person");
        jPanel8.add(jLabel4);

        jPanel7.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jTextField3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField3.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel9.add(jTextField3);

        jPanel7.add(jPanel9);

        jPanel6.add(jPanel7);

        getContentPane().add(jPanel6);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        jPanel12.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Dog");
        jPanel12.add(jLabel5);

        jPanel11.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jTextField4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField4.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel13.add(jTextField4);

        jPanel11.add(jPanel13);

        jPanel10.add(jPanel11);

        getContentPane().add(jPanel10);

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setLayout(new java.awt.GridLayout(1, 2));

        jPanel16.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Treatment Type");
        jPanel16.add(jLabel6);

        jPanel15.add(jPanel16);

        jPanel17.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jTextField5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField5.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel17.add(jTextField5);

        jPanel15.add(jPanel17);

        jPanel14.add(jPanel15);

        getContentPane().add(jPanel14);

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setLayout(new java.awt.GridLayout(1, 2));

        jPanel20.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Fee");
        jPanel20.add(jLabel7);

        jPanel19.add(jPanel20);

        jPanel21.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField6.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel21.add(jTextField6);

        jPanel19.add(jPanel21);

        jPanel18.add(jPanel19);

        getContentPane().add(jPanel18);

        jPanel23.setBackground(new java.awt.Color(204, 204, 204));
        jPanel23.setLayout(new java.awt.GridLayout(1, 2));

        jPanel24.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Duration");
        jPanel24.add(jLabel8);

        jPanel23.add(jPanel24);

        jPanel25.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField7.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel25.add(jTextField7);

        jPanel23.add(jPanel25);

        jPanel22.add(jPanel23);

        getContentPane().add(jPanel22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
