package javadoggroomingapp.ui;

import java.awt.Font;
import java.util.List;
import javadoggroomingapp.domain.Appointment;
import javadoggroomingapp.domain.Salon;
import javadoggroomingapp.domain.User;
import javadoggroomingapp.domain.TreatmentType;
import javadoggroomingapp.repository.DatabaseRepository;
import javadoggroomingapp.ui.components.table.model.AppointmentTableModel;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Lenovo
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     * @param currentUser
     */
    public MainForm(User currentUser) {

        for (Salon s : new DatabaseRepository().getSalons()) {
            System.out.println(s.toString());
        }

        initComponents();
        System.out.println("Logged in as: " + currentUser.getUsername());
        populateForm();
        populateComboSalonFilter();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbSalonFilter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(850, 700));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Future appointments");

        cmbSalonFilter.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Choose a salon:");

        tblAppointments.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAppointments.setRowHeight(30);
        jScrollPane1.setViewportView(tblAppointments);

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setText("Add new appointment");

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton2.setText("Remove appointment");

        jButton3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton3.setText("Edit appointment");

        jMenuBar1.setBorder(null);

        jMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu1.setText("Persons");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem1.setText("View all persons");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dogs");
        jMenu2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Salons");
        jMenu4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Price Rates Iformation");
        jMenu3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbSalonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(577, 577, 577)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(97, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmbSalonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSalonFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAppointments;
    // End of variables declaration//GEN-END:variables

    private void populateForm() {
        try {
            List<Appointment> appointments = new DatabaseRepository().getAppointments();
            tblAppointments.setModel(new AppointmentTableModel(appointments));
            tblAppointments.setAutoCreateRowSorter(true);

            fillComboDog();
            fillComboSalon();
            fillComboTreatmentType();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void populateComboSalonFilter() {
        cmbSalonFilter.setModel(new DefaultComboBoxModel(new DatabaseRepository().getSalons().toArray()));
    }

    private void fillComboDog() {
        TableColumnModel tcm = tblAppointments.getColumnModel();
        TableColumn columnDog = tcm.getColumn(1);

        JComboBox comboDog = new JComboBox(new DefaultComboBoxModel(new DatabaseRepository().getDogs().toArray()));
        columnDog.setCellEditor(new DefaultCellEditor(comboDog));
        comboDog.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));
        
    }

    private void fillComboSalon() {
        TableColumnModel tcm = tblAppointments.getColumnModel();
        TableColumn columnDog = tcm.getColumn(2);

        JComboBox comboSalon = new JComboBox(new DefaultComboBoxModel(new DatabaseRepository().getSalons().toArray()));
        columnDog.setCellEditor(new DefaultCellEditor(comboSalon));
        comboSalon.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));
    }

    private void fillComboTreatmentType() {
        TableColumnModel tcm = tblAppointments.getColumnModel();
        TableColumn columnDog = tcm.getColumn(5);

        JComboBox comboTreatmentType = new JComboBox(new DefaultComboBoxModel(TreatmentType.values()));
        columnDog.setCellEditor(new DefaultCellEditor(comboTreatmentType));
        comboTreatmentType.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));
    }
}
