package javadoggroomingapp.ui;

import java.awt.Font;
import java.time.LocalDateTime;
import java.util.List;
import javadoggroomingapp.domain.Appointment;
import javadoggroomingapp.domain.Dog;
import javadoggroomingapp.domain.Salon;
import javadoggroomingapp.domain.User;
import javadoggroomingapp.domain.TreatmentType;
import javadoggroomingapp.repository.DatabaseRepository;
import javadoggroomingapp.ui.components.table.model.AppointmentTableModel;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Lenovo
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     *
     * @param currentUser
     */
    public MainForm(User currentUser) {

        for (Salon s : new DatabaseRepository().getSalons()) {
            System.out.println(s.toString());
        }

        initComponents();
        System.out.println("Logged in as: " + currentUser.getUsername());
        populateTable();
        populateComboSalonFilter();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbSalonFilter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        btnAddAppointment = new javax.swing.JButton();
        btnRemoveAppointment = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        brtViewAll = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(850, 700));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Future appointments");

        cmbSalonFilter.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cmbSalonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSalonFilterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Choose a salon:");

        tblAppointments.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAppointments.setRowHeight(30);
        jScrollPane1.setViewportView(tblAppointments);

        btnAddAppointment.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAddAppointment.setText("Add new appointment");
        btnAddAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAppointmentActionPerformed(evt);
            }
        });

        btnRemoveAppointment.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnRemoveAppointment.setText("Cancel appointment");
        btnRemoveAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAppointmentActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton3.setText("Edit appointment");
        jButton3.setMaximumSize(new java.awt.Dimension(164, 27));
        jButton3.setMinimumSize(new java.awt.Dimension(164, 27));

        brtViewAll.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        brtViewAll.setText("View All");
        brtViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtViewAllActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(null);

        jMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu1.setText("Persons");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem1.setText("View all persons");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dogs");
        jMenu2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Salons");
        jMenu4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Price Rates Information");
        jMenu3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddAppointment))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSalonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(brtViewAll)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(723, 723, 723)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemoveAppointment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(97, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddAppointment)
                        .addGap(18, 18, 18)))
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmbSalonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brtViewAll))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRemoveAppointment)
                        .addGap(47, 47, 47)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSalonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSalonFilterActionPerformed
        Salon selectedSalon = (Salon) cmbSalonFilter.getSelectedItem();
        populateForm(selectedSalon);
    }//GEN-LAST:event_cmbSalonFilterActionPerformed

    private void brtViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brtViewAllActionPerformed
        Salon selectedSalon = (Salon) cmbSalonFilter.getSelectedItem();
        if (selectedSalon == null) {
            return;
        }
        populateTable();
    }//GEN-LAST:event_brtViewAllActionPerformed

    private void btnRemoveAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAppointmentActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel this appointment?") == 0) {
            AppointmentTableModel appointmentTableModel = (AppointmentTableModel) tblAppointments.getModel();
            int selectedAppointment = tblAppointments.getRowSorter().convertRowIndexToModel(tblAppointments.getSelectedRow());
            appointmentTableModel.remove(selectedAppointment);
        }


    }//GEN-LAST:event_btnRemoveAppointmentActionPerformed

    private void btnAddAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAppointmentActionPerformed
        AppointmentTableModel appointmentTableModel = (AppointmentTableModel) tblAppointments.getModel();
        Dog dog = new DatabaseRepository().getDogs().get(0);
        Salon salon = new DatabaseRepository().getSalons().get(0);
        LocalDateTime dateTime = LocalDateTime.now();
        TreatmentType treatmentType = TreatmentType.AESTHETIC;
        Appointment appointment = new Appointment();
        appointment.setDog(dog);
        appointment.setSalon(salon);
        appointment.setDateTime(dateTime);
        appointment.setTreatmentType(treatmentType);
        appointmentTableModel.add(appointment);
    }//GEN-LAST:event_btnAddAppointmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtViewAll;
    private javax.swing.JButton btnAddAppointment;
    private javax.swing.JButton btnRemoveAppointment;
    private javax.swing.JComboBox<String> cmbSalonFilter;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAppointments;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        try {
            List<Appointment> appointments = new DatabaseRepository().getAppointments();
            tblAppointments.setModel(new AppointmentTableModel(appointments));
            tblAppointments.setAutoCreateRowSorter(true);
            tblAppointments.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            fillComboDog();
            fillComboSalon();
            fillComboTreatmentType();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void populateForm(Salon salonFilter) {
        try {
            List<Appointment> appointments = new DatabaseRepository().getAppointments(salonFilter);
            tblAppointments.setModel(new AppointmentTableModel(appointments));
            tblAppointments.setAutoCreateRowSorter(true);

            fillComboDog();
            fillComboSalon();
            fillComboTreatmentType();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void populateComboSalonFilter() {
        cmbSalonFilter.setModel(new DefaultComboBoxModel(new DatabaseRepository().getSalons().toArray()));
        cmbSalonFilter.setSelectedItem(null);
    }

    private void fillComboDog() {
        TableColumnModel tcm = tblAppointments.getColumnModel();
        TableColumn columnDog = tcm.getColumn(1);

        JComboBox comboDog = new JComboBox(new DefaultComboBoxModel(new DatabaseRepository().getDogs().toArray()));
        columnDog.setCellEditor(new DefaultCellEditor(comboDog));
        comboDog.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));

    }

    private void fillComboSalon() {
        TableColumnModel tcm = tblAppointments.getColumnModel();
        TableColumn columnDog = tcm.getColumn(2);

        JComboBox comboSalon = new JComboBox(new DefaultComboBoxModel(new DatabaseRepository().getSalons().toArray()));
        columnDog.setCellEditor(new DefaultCellEditor(comboSalon));
        comboSalon.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));
    }

    private void fillComboTreatmentType() {
        TableColumnModel tcm = tblAppointments.getColumnModel();
        TableColumn columnDog = tcm.getColumn(5);

        JComboBox comboTreatmentType = new JComboBox(new DefaultComboBoxModel(TreatmentType.values()));
        columnDog.setCellEditor(new DefaultCellEditor(comboTreatmentType));
        comboTreatmentType.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));
    }
}
